#!/bin/sh
# Copyright (C) 2016-2018, TOSHIBA Corp., Daniel Sangorrin <daniel.sangorrin@toshiba.co.jp>
# SPDX-License-Identifier:	MIT
# minimal bootup script to mount file systems

# mount filesystem
echo "Mounting filesystem..."
if [ ! -d /dev/shm ]; then mkdir -p /dev/shm; fi
if [ ! -d /dev/pts ]; then mkdir -p /dev/pts; fi
mount -a

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

mkdir /run/lock
mkdir /run/sshd

# set hostname so that hostid works (tuned for CIP)
hostname ciphost

# sysctl settings
/etc/init.d/procps start

# start logger. Note that logs do not persist across boots.
/sbin/klogd
/sbin/syslogd

# rise up all network interfaces available
ifup -a

# start the ssh server
/etc/init.d/ssh start
