#!/usr/bin/env python3
# EASY-INSTALL-ENTRY-SCRIPT: 'wirepas-gateway==1.1.0','console_scripts','wm-gw'
__requires__ = 'wirepas-gateway==1.1.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('wirepas-gateway==1.1.0', 'console_scripts', 'wm-gw')()
    )
